// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services.proto

package TermChat

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TODO: Move messages into different files
// ----------------------------------------------------------------------------
type PersonalInfo struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Age                  uint32   `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonalInfo) Reset()         { *m = PersonalInfo{} }
func (m *PersonalInfo) String() string { return proto.CompactTextString(m) }
func (*PersonalInfo) ProtoMessage()    {}
func (*PersonalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{0}
}

func (m *PersonalInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonalInfo.Unmarshal(m, b)
}
func (m *PersonalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonalInfo.Marshal(b, m, deterministic)
}
func (m *PersonalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonalInfo.Merge(m, src)
}
func (m *PersonalInfo) XXX_Size() int {
	return xxx_messageInfo_PersonalInfo.Size(m)
}
func (m *PersonalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PersonalInfo proto.InternalMessageInfo

func (m *PersonalInfo) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *PersonalInfo) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *PersonalInfo) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *PersonalInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type User struct {
	UniqueId             uint32        `protobuf:"varint,1,opt,name=uniqueId,proto3" json:"uniqueId,omitempty"`
	LoginId              string        `protobuf:"bytes,2,opt,name=loginId,proto3" json:"loginId,omitempty"`
	PersonalInfo         *PersonalInfo `protobuf:"bytes,3,opt,name=personalInfo,proto3" json:"personalInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUniqueId() uint32 {
	if m != nil {
		return m.UniqueId
	}
	return 0
}

func (m *User) GetLoginId() string {
	if m != nil {
		return m.LoginId
	}
	return ""
}

func (m *User) GetPersonalInfo() *PersonalInfo {
	if m != nil {
		return m.PersonalInfo
	}
	return nil
}

// ----------------------------------------------------------------------------
type GetFriendsRequest struct {
	TokenId              string   `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFriendsRequest) Reset()         { *m = GetFriendsRequest{} }
func (m *GetFriendsRequest) String() string { return proto.CompactTextString(m) }
func (*GetFriendsRequest) ProtoMessage()    {}
func (*GetFriendsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{2}
}

func (m *GetFriendsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendsRequest.Unmarshal(m, b)
}
func (m *GetFriendsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendsRequest.Marshal(b, m, deterministic)
}
func (m *GetFriendsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendsRequest.Merge(m, src)
}
func (m *GetFriendsRequest) XXX_Size() int {
	return xxx_messageInfo_GetFriendsRequest.Size(m)
}
func (m *GetFriendsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendsRequest proto.InternalMessageInfo

func (m *GetFriendsRequest) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

type GetFriendsResponse struct {
	Friends              []*User  `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFriendsResponse) Reset()         { *m = GetFriendsResponse{} }
func (m *GetFriendsResponse) String() string { return proto.CompactTextString(m) }
func (*GetFriendsResponse) ProtoMessage()    {}
func (*GetFriendsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{3}
}

func (m *GetFriendsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendsResponse.Unmarshal(m, b)
}
func (m *GetFriendsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendsResponse.Marshal(b, m, deterministic)
}
func (m *GetFriendsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendsResponse.Merge(m, src)
}
func (m *GetFriendsResponse) XXX_Size() int {
	return xxx_messageInfo_GetFriendsResponse.Size(m)
}
func (m *GetFriendsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendsResponse proto.InternalMessageInfo

func (m *GetFriendsResponse) GetFriends() []*User {
	if m != nil {
		return m.Friends
	}
	return nil
}

// ----------------------------------------------------------------------------
type AddFriendRequest struct {
	TokenId              string   `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFriendRequest) Reset()         { *m = AddFriendRequest{} }
func (m *AddFriendRequest) String() string { return proto.CompactTextString(m) }
func (*AddFriendRequest) ProtoMessage()    {}
func (*AddFriendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{4}
}

func (m *AddFriendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFriendRequest.Unmarshal(m, b)
}
func (m *AddFriendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFriendRequest.Marshal(b, m, deterministic)
}
func (m *AddFriendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFriendRequest.Merge(m, src)
}
func (m *AddFriendRequest) XXX_Size() int {
	return xxx_messageInfo_AddFriendRequest.Size(m)
}
func (m *AddFriendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFriendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFriendRequest proto.InternalMessageInfo

func (m *AddFriendRequest) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

type AddFriendResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFriendResponse) Reset()         { *m = AddFriendResponse{} }
func (m *AddFriendResponse) String() string { return proto.CompactTextString(m) }
func (*AddFriendResponse) ProtoMessage()    {}
func (*AddFriendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{5}
}

func (m *AddFriendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFriendResponse.Unmarshal(m, b)
}
func (m *AddFriendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFriendResponse.Marshal(b, m, deterministic)
}
func (m *AddFriendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFriendResponse.Merge(m, src)
}
func (m *AddFriendResponse) XXX_Size() int {
	return xxx_messageInfo_AddFriendResponse.Size(m)
}
func (m *AddFriendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFriendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddFriendResponse proto.InternalMessageInfo

func (m *AddFriendResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// ----------------------------------------------------------------------------
type RemoveFriendRequest struct {
	TokenId              string   `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFriendRequest) Reset()         { *m = RemoveFriendRequest{} }
func (m *RemoveFriendRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFriendRequest) ProtoMessage()    {}
func (*RemoveFriendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{6}
}

func (m *RemoveFriendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFriendRequest.Unmarshal(m, b)
}
func (m *RemoveFriendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFriendRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFriendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFriendRequest.Merge(m, src)
}
func (m *RemoveFriendRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFriendRequest.Size(m)
}
func (m *RemoveFriendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFriendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFriendRequest proto.InternalMessageInfo

func (m *RemoveFriendRequest) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

type RemoveFriendResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFriendResponse) Reset()         { *m = RemoveFriendResponse{} }
func (m *RemoveFriendResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveFriendResponse) ProtoMessage()    {}
func (*RemoveFriendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{7}
}

func (m *RemoveFriendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFriendResponse.Unmarshal(m, b)
}
func (m *RemoveFriendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFriendResponse.Marshal(b, m, deterministic)
}
func (m *RemoveFriendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFriendResponse.Merge(m, src)
}
func (m *RemoveFriendResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveFriendResponse.Size(m)
}
func (m *RemoveFriendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFriendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFriendResponse proto.InternalMessageInfo

func (m *RemoveFriendResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// ----------------------------------------------------------------------------
type ListUsersRequest struct {
	TokenId              string   `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{8}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

func (m *ListUsersRequest) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

type ListUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{9}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*PersonalInfo)(nil), "PersonalInfo")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*GetFriendsRequest)(nil), "GetFriendsRequest")
	proto.RegisterType((*GetFriendsResponse)(nil), "GetFriendsResponse")
	proto.RegisterType((*AddFriendRequest)(nil), "AddFriendRequest")
	proto.RegisterType((*AddFriendResponse)(nil), "AddFriendResponse")
	proto.RegisterType((*RemoveFriendRequest)(nil), "RemoveFriendRequest")
	proto.RegisterType((*RemoveFriendResponse)(nil), "RemoveFriendResponse")
	proto.RegisterType((*ListUsersRequest)(nil), "ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "ListUsersResponse")
}

func init() {
	proto.RegisterFile("services.proto", fileDescriptor_8e16ccb8c5307b32)
}

var fileDescriptor_8e16ccb8c5307b32 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x4f, 0x6f, 0x13, 0x31,
	0x10, 0xc5, 0xb3, 0xa4, 0x21, 0xcd, 0x34, 0x81, 0xec, 0x34, 0x48, 0xab, 0x05, 0x89, 0xc8, 0xa7,
	0x1c, 0x5a, 0x03, 0x01, 0xc4, 0x89, 0x03, 0x20, 0x81, 0x22, 0x21, 0x84, 0x2c, 0xb8, 0x70, 0x33,
	0xdd, 0x49, 0xb0, 0xd8, 0xb5, 0x53, 0xdb, 0xe9, 0x37, 0xe7, 0x8e, 0xbc, 0x7f, 0xd2, 0x4d, 0xb7,
	0x52, 0x7b, 0xcb, 0x7b, 0x7e, 0x9e, 0x97, 0xf9, 0x59, 0x0b, 0x8f, 0x1c, 0xd9, 0x2b, 0x75, 0x41,
	0x8e, 0x6f, 0xad, 0xf1, 0x86, 0x6d, 0x61, 0xfc, 0x9d, 0xac, 0x33, 0x5a, 0xe6, 0x2b, 0xbd, 0x36,
	0xf8, 0x0c, 0x46, 0x6b, 0x65, 0x9d, 0xff, 0x26, 0x0b, 0x4a, 0xa2, 0x79, 0xb4, 0x18, 0x89, 0x6b,
	0x03, 0x53, 0x38, 0xce, 0x65, 0x7d, 0xf8, 0xa0, 0x3c, 0xdc, 0x6b, 0x9c, 0x42, 0x5f, 0x6e, 0x28,
	0xe9, 0xcf, 0xa3, 0xc5, 0x44, 0x84, 0x9f, 0x38, 0x83, 0x01, 0x15, 0x52, 0xe5, 0xc9, 0x51, 0x19,
	0xad, 0x04, 0x33, 0x70, 0xf4, 0xd3, 0x91, 0x0d, 0xb3, 0x76, 0x5a, 0x5d, 0xee, 0x68, 0x95, 0x95,
	0x45, 0x13, 0xb1, 0xd7, 0x98, 0xc0, 0x30, 0x37, 0x1b, 0xa5, 0x57, 0x59, 0x5d, 0xd3, 0x48, 0x7c,
	0x05, 0xe3, 0x6d, 0xeb, 0xff, 0x96, 0x75, 0x27, 0xcb, 0x09, 0x6f, 0x2f, 0x21, 0x0e, 0x22, 0xec,
	0x1c, 0xe2, 0x2f, 0xe4, 0x3f, 0x5b, 0x45, 0x3a, 0x73, 0x82, 0x2e, 0x77, 0xe4, 0x7c, 0x68, 0xf0,
	0xe6, 0x2f, 0xe9, 0xba, 0x7c, 0x24, 0x1a, 0xc9, 0xde, 0x02, 0xb6, 0xe3, 0x6e, 0x6b, 0xb4, 0x23,
	0x7c, 0x0e, 0xc3, 0x75, 0x65, 0x25, 0xd1, 0xbc, 0xbf, 0x38, 0x59, 0x0e, 0x78, 0xd8, 0x42, 0x34,
	0x2e, 0x3b, 0x83, 0xe9, 0x87, 0x2c, 0xab, 0xae, 0xdd, 0x5d, 0x72, 0x0e, 0x71, 0x2b, 0x5d, 0x77,
	0x24, 0x30, 0x2c, 0xc8, 0xb9, 0x40, 0xb1, 0x8e, 0xd7, 0x92, 0xbd, 0x80, 0x53, 0x41, 0x85, 0xb9,
	0xa2, 0xfb, 0xce, 0x7f, 0x09, 0xb3, 0xc3, 0x0b, 0x77, 0x56, 0x9c, 0xc1, 0xf4, 0xab, 0x72, 0x3e,
	0x2c, 0xe5, 0xee, 0x33, 0x3f, 0x6e, 0xa5, 0xeb, 0xe1, 0x4f, 0x61, 0xb0, 0x0b, 0xc6, 0x21, 0xa1,
	0xca, 0x5b, 0xfe, 0x8b, 0xe0, 0x71, 0xd0, 0x2b, 0xed, 0xc9, 0xca, 0x0b, 0xaf, 0x8c, 0xc6, 0x77,
	0x00, 0x9b, 0x3d, 0x6a, 0x44, 0xde, 0x79, 0xa6, 0xf4, 0x94, 0x77, 0xdf, 0x82, 0xf5, 0xf0, 0x0d,
	0x8c, 0x64, 0x83, 0x0f, 0x63, 0x7e, 0x13, 0x7c, 0x8a, 0xbc, 0x43, 0x97, 0xf5, 0xf0, 0x3d, 0x8c,
	0x6d, 0x0b, 0x0a, 0xce, 0xf8, 0x2d, 0x50, 0xd3, 0x27, 0xfc, 0x36, 0x72, 0x55, 0x69, 0xde, 0xec,
	0x8c, 0x31, 0xbf, 0x49, 0x2b, 0x45, 0xde, 0x41, 0xc2, 0x7a, 0x1f, 0xe1, 0xd7, 0xf1, 0x0f, 0xb2,
	0xc5, 0xa7, 0x3f, 0xd2, 0xff, 0x7e, 0x58, 0x7e, 0x73, 0xaf, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff,
	0x30, 0xb0, 0x31, 0x92, 0x85, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserInteractionClient is the client API for UserInteraction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserInteractionClient interface {
	GetFriends(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*GetFriendsResponse, error)
	AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error)
	RemoveFriend(ctx context.Context, in *RemoveFriendRequest, opts ...grpc.CallOption) (*RemoveFriendResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
}

type userInteractionClient struct {
	cc grpc.ClientConnInterface
}

func NewUserInteractionClient(cc grpc.ClientConnInterface) UserInteractionClient {
	return &userInteractionClient{cc}
}

func (c *userInteractionClient) GetFriends(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*GetFriendsResponse, error) {
	out := new(GetFriendsResponse)
	err := c.cc.Invoke(ctx, "/UserInteraction/getFriends", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInteractionClient) AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error) {
	out := new(AddFriendResponse)
	err := c.cc.Invoke(ctx, "/UserInteraction/addFriend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInteractionClient) RemoveFriend(ctx context.Context, in *RemoveFriendRequest, opts ...grpc.CallOption) (*RemoveFriendResponse, error) {
	out := new(RemoveFriendResponse)
	err := c.cc.Invoke(ctx, "/UserInteraction/removeFriend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInteractionClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/UserInteraction/listUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserInteractionServer is the server API for UserInteraction service.
type UserInteractionServer interface {
	GetFriends(context.Context, *GetFriendsRequest) (*GetFriendsResponse, error)
	AddFriend(context.Context, *AddFriendRequest) (*AddFriendResponse, error)
	RemoveFriend(context.Context, *RemoveFriendRequest) (*RemoveFriendResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
}

// UnimplementedUserInteractionServer can be embedded to have forward compatible implementations.
type UnimplementedUserInteractionServer struct {
}

func (*UnimplementedUserInteractionServer) GetFriends(ctx context.Context, req *GetFriendsRequest) (*GetFriendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFriends not implemented")
}
func (*UnimplementedUserInteractionServer) AddFriend(ctx context.Context, req *AddFriendRequest) (*AddFriendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFriend not implemented")
}
func (*UnimplementedUserInteractionServer) RemoveFriend(ctx context.Context, req *RemoveFriendRequest) (*RemoveFriendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFriend not implemented")
}
func (*UnimplementedUserInteractionServer) ListUsers(ctx context.Context, req *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}

func RegisterUserInteractionServer(s *grpc.Server, srv UserInteractionServer) {
	s.RegisterService(&_UserInteraction_serviceDesc, srv)
}

func _UserInteraction_GetFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInteractionServer).GetFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserInteraction/GetFriends",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInteractionServer).GetFriends(ctx, req.(*GetFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInteraction_AddFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInteractionServer).AddFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserInteraction/AddFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInteractionServer).AddFriend(ctx, req.(*AddFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInteraction_RemoveFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInteractionServer).RemoveFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserInteraction/RemoveFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInteractionServer).RemoveFriend(ctx, req.(*RemoveFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInteraction_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInteractionServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserInteraction/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInteractionServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserInteraction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserInteraction",
	HandlerType: (*UserInteractionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getFriends",
			Handler:    _UserInteraction_GetFriends_Handler,
		},
		{
			MethodName: "addFriend",
			Handler:    _UserInteraction_AddFriend_Handler,
		},
		{
			MethodName: "removeFriend",
			Handler:    _UserInteraction_RemoveFriend_Handler,
		},
		{
			MethodName: "listUsers",
			Handler:    _UserInteraction_ListUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}
